Add non-SMF init script and hooks

diff --git a/smf/postgres_og b/smf/postgres_og
--- a/smf/postgres_og
+++ b/smf/postgres_og
@@ -10,32 +10,23 @@
 # SMF_FMRI is the name of the target service. This allows multiple instances 
 # to use the same script.
 
-usage() {
-  echo "usage: $0 -D /pgsql/data/path -B /pgsql/bin/path -L /pgsql/log/path"
-  echo ""
-  echo "   This script must be run as the 'postgres' user. "
-  echo "   If run without arguments, it will read startup values from"
-  echo "   the SMF system."
-  echo ""
-}
-
 getproparg() {
         val=`svcprop -p $1 $SMF_FMRI`
         [ -n "$val" ] && echo $val
 }
 
 check_data_dir() {
+	if [ ! -w $PGDATA ]; then
+		echo "Error: postgresql_og/data directory $PGDATA is not writable by postgres"
+		exit $SMF_EXIT_ERR_CONFIG
+	fi
+
 	if [ ! -d $PGDATA ]; then
                 /bin/mkdir $PGDATA
 		if [ ! -d $PGDATA ]; then
 			echo "Error: postgresql_og/data directory $PGDATA does not exist and could not be created"
 			exit $SMF_EXIT_ERR_CONFIG
 		fi
-	fi
-
-	if [ ! -w $PGDATA ]; then
-		echo "Error: postgresql_og/data directory $PGDATA is not writable by postgres"
-		exit $SMF_EXIT_ERR_CONFIG
 	fi
 
 	if [ ! -d $PGDATA/base -o ! -d $PGDATA/global -o ! -f $PGDATA/PG_VERSION ]; then
@@ -57,39 +48,9 @@ check_data_dir() {
 	fi
 }
 
-id=`id | grep postgres`
-
-# Read important variables from the commandline
-while getopts B:D:L: opt
-do
-  case "$opt" in
-    B) PGBIN=$OPTARG;;
-    D) PGDATA=$OPTARG;;
-    L) PGLOG=$OPTARG;;
-    *) usage;;
-  esac
-done
-
-# We have to run this script as postgres
-if [ "x" == "x$id" ]; then
-  echo "Error: $0 must be run as user 'postgres'"
-  exit $SMF_EXIT_ERR
-fi
-
-# Read the important variables from SMF if they aren't provided on the
-# commandline
-if [ ! -n $PGBIN ]; then
-  PGBIN=`getproparg postgresql_og/bin`
-  COMMANDLINE=1
-fi
-if [ ! -n $PGDATA ]; then
-  PGDATA=`getproparg postgresql_og/data`
-  COMMANDLINE=1
-fi
-if [ ! -n $PGLOG ]; then
-  PGLOG=`getproparg postgresql_og/log`
-  COMMANDLINE=1
-fi
+PGBIN=`getproparg postgresql_og/bin`
+PGDATA=`getproparg postgresql_og/data`
+PGLOG=`getproparg postgresql_og/log`
 
 if [ -z $SMF_FMRI ]; then
 	echo "Error: SMF framework variables are not initialized"
@@ -101,7 +62,7 @@ if [ -z $PGDATA ]; then
         exit $SMF_EXIT_ERR_CONFIG
 fi
 
-if [ ! -n $COMMANDLINE ] && [ -z $PGLOG ]; then
+if [ -z $PGLOG ]; then
         echo "Error: postgresql_og/log property not set"
         exit $SMF_EXIT_ERR_CONFIG
 fi
